# Generated by Django 6.0.5 on 2026-05-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pc_type',
            field=models.CharField(blank=True, choices=[('gpu', 'GPU'), ('cpu', 'CPU'), ('ram', 'RAM'), ('motherboard', 'Motherboard'), ('storage', 'Storage'), ('psu', 'PSU'), ('case', 'Case'), ('cooling', 'Cooling')], max_length=50, null=True),
        ),
    ]
